apiVersion: v1
kind: Service
metadata:
  name: {{ include "laya.fullname" . }}-api
  labels:
    {{- include "laya.labels" (dict "root" . "component" "api") | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 8080
      targetPort: http
  selector:
    {{- include "laya.selectorLabels" (dict "root" . "component" "api") | nindent 4 }}
